version: '3.1'
services:
  web:
    container_name: odoo15
    image: odoo:15.0
    build: ./
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./project:/mnt/project
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./addons-customize:/mnt/extra-addons-customize
    environment:
      - VIRTUAL_HOST=odoo14.escuelafullstack.com
    entrypoint: "/usr/bin/odoo -c /etc/odoo/odoo.conf"
    restart: always
  db:
    container_name: odoo_v15_db
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    restart: always
volumes:
  odoo-db-data:
  odoo-web-data:
